## Reshape()

In [1]:
import torch

In [4]:
# reshape
x = torch.arange(12)
y = x.reshape(3,4)

In [5]:
x,y

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [8]:
x =  torch.arange(24)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [10]:
y = x.reshape(4,6)
y

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

In [12]:
z = x.reshape(2,3,4)
z

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [14]:
q = x.reshape(3,-1)
q, q.shape

(tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20, 21, 22, 23]]),
 torch.Size([3, 8]))

In [15]:
q_1 = q.reshape(-1)

In [16]:
q_1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

## Flatten()

In [17]:
import torch

In [24]:
x = torch.arange(24)
x = x.reshape(4,6)
print(x.shape)

flat = x.flatten()
print(flat)
print(flat.shape)

torch.Size([4, 6])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
torch.Size([24])


In [29]:
# Flatten a part

x = torch.arange(24)
x = x.reshape(2,3,2,2)
print(x)

x = x.flatten(start_dim=1)
x

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]],


        [[[12, 13],
          [14, 15]],

         [[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]]])


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [30]:
x = torch.arange(24).reshape(2,3,4)

print(x.flatten())
print(x.flatten(start_dim=1))
print(x.reshape(-1))


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])


## Squeeze và Unsqueeze

In [33]:
x = torch.arange(3)
x, x.shape

(tensor([0, 1, 2]), torch.Size([3]))

In [34]:
x = x.unsqueeze(0)
x.shape

torch.Size([1, 3])

In [35]:
x = torch.tensor([10,20,30])
x

tensor([10, 20, 30])

In [ ]:
x = x.unsqueeze(0)

In [41]:
print(x.shape)

y = torch.zeros(3,3)
x + y

torch.Size([1, 3])


tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])

In [43]:
x = torch.rand(24)
x.shape

torch.Size([24])

In [ ]:
x = x.unsqueeze(1)
x

tensor([[0.4821],
        [0.5580],
        [0.5093],
        [0.9837],
        [0.3671],
        [0.2122],
        [0.8204],
        [0.3207],
        [0.0800],
        [0.8898],
        [0.9732],
        [0.7939],
        [0.8666],
        [0.5239],
        [0.2938],
        [0.5458],
        [0.1744],
        [0.5288],
        [0.5756],
        [0.4418],
        [0.9780],
        [0.4062],
        [0.2265],
        [0.5779]])

In [ ]:
x = torch.rand(4,3)
print(x)

y = x.unsqueeze(1)
print(y.shape)



tensor([[0.8129, 0.7230, 0.6484],
        [0.9876, 0.9393, 0.6434],
        [0.8770, 0.5814, 0.6822],
        [0.9745, 0.6407, 0.6976]])
torch.Size([4, 1, 3])


In [49]:
z = torch.rand(4,5,3)
z

tensor([[[0.9902, 0.6938, 0.0101],
         [0.5965, 0.3079, 0.3650],
         [0.4229, 0.4094, 0.3270],
         [0.3588, 0.1910, 0.4153],
         [0.7229, 0.8840, 0.3821]],

        [[0.1020, 0.6353, 0.5848],
         [0.8420, 0.2072, 0.3270],
         [0.5203, 0.0600, 0.7611],
         [0.3653, 0.1529, 0.6762],
         [0.4834, 0.9634, 0.4451]],

        [[0.8483, 0.5503, 0.1645],
         [0.8759, 0.4985, 0.9118],
         [0.3495, 0.5698, 0.6222],
         [0.2601, 0.4985, 0.9203],
         [0.6213, 0.4553, 0.3207]],

        [[0.8379, 0.8063, 0.7900],
         [0.3642, 0.5465, 0.7061],
         [0.5687, 0.8083, 0.8626],
         [0.9159, 0.0907, 0.9068],
         [0.4346, 0.3694, 0.3658]]])

In [50]:
y + z

tensor([[[1.8031, 1.4168, 0.6585],
         [1.4094, 1.0310, 1.0135],
         [1.2358, 1.1324, 0.9754],
         [1.1716, 0.9140, 1.0637],
         [1.5357, 1.6070, 1.0305]],

        [[1.0896, 1.5746, 1.2282],
         [1.8296, 1.1465, 0.9704],
         [1.5079, 0.9993, 1.4045],
         [1.3529, 1.0922, 1.3196],
         [1.4710, 1.9027, 1.0886]],

        [[1.7253, 1.1317, 0.8467],
         [1.7530, 1.0799, 1.5941],
         [1.2265, 1.1511, 1.3044],
         [1.1372, 1.0799, 1.6025],
         [1.4983, 1.0367, 1.0030]],

        [[1.8124, 1.4471, 1.4876],
         [1.3388, 1.1872, 1.4037],
         [1.5432, 1.4491, 1.5602],
         [1.8904, 0.7314, 1.6044],
         [1.4091, 1.0101, 1.0634]]])